name: regex
version: 1.0.1
description: Regular Expression Plugin for PolymorphicBot
dependencies:
  irc: '>=2.0.0 <3.0.0'
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
  quiver: '>=0.19.0 <0.25.0'
plugin:
  dependencies:
  - buffer
